# Generated by Django 5.1.3 on 2024-11-21 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctornotification',
            old_name='name',
            new_name='uname',
        ),
    ]
