# Generated by Django 5.1.3 on 2024-11-21 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0002_rename_name_doctornotification_uname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctornotification',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_app.department'),
        ),
    ]
