# Generated by Django 5.1.3 on 2024-11-22 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0003_alter_doctornotification_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=22225, null=True)),
                ('image', models.ImageField(null=True, upload_to='Image/')),
                ('resume', models.FileField(null=True, upload_to='Resume/')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_app.department')),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hospital_app.userprofile')),
            ],
        ),
    ]
