# Generated by Django 5.1.3 on 2024-11-22 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0004_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacistNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=35, null=True)),
                ('lname', models.CharField(max_length=35, null=True)),
                ('uname', models.CharField(max_length=35, null=True)),
                ('email', models.CharField(max_length=55, null=True)),
                ('address', models.CharField(max_length=22225, null=True)),
                ('image', models.ImageField(null=True, upload_to='Image/')),
                ('resume', models.FileField(null=True, upload_to='Resume/')),
            ],
        ),
        migrations.CreateModel(
            name='ReceptionistNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=35, null=True)),
                ('lname', models.CharField(max_length=35, null=True)),
                ('uname', models.CharField(max_length=35, null=True)),
                ('email', models.CharField(max_length=55, null=True)),
                ('address', models.CharField(max_length=22225, null=True)),
                ('image', models.ImageField(null=True, upload_to='Image/')),
                ('resume', models.FileField(null=True, upload_to='Resume/')),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=22225, null=True)),
                ('image', models.ImageField(null=True, upload_to='Image/')),
                ('resume', models.FileField(null=True, upload_to='Resume/')),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hospital_app.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Receptionist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=22225, null=True)),
                ('image', models.ImageField(null=True, upload_to='Image/')),
                ('resume', models.FileField(null=True, upload_to='Resume/')),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hospital_app.userprofile')),
            ],
        ),
    ]
