# Generated by Django 5.1.3 on 2024-11-24 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0007_appointment_medicalhistory_waitinglist'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_inpatient',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_id',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
