# Generated by Django 5.1.3 on 2024-11-28 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0010_delete_waitinglist'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('General', 'General'), ('ICU', 'ICU'), ('Private', 'Private')], max_length=20)),
                ('total_rooms', models.PositiveIntegerField(default=0)),
                ('available_rooms', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BedAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_date', models.DateTimeField(auto_now_add=True)),
                ('discharged_date', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_app.patient')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_app.roomtype')),
            ],
        ),
    ]
