# Generated by Django 5.1.3 on 2024-11-28 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0012_alter_roomtype_room_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine', models.CharField(blank=True, max_length=20, null=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('rate', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='prescriptions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital_app.prescription'),
        ),
    ]
