# Generated by Django 5.1.3 on 2024-11-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0013_prescription_alter_medicalhistory_prescriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='rate_per_day',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
