# Generated by Django 5.1.3 on 2024-11-28 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0014_roomtype_rate_per_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalhistory',
            name='prescriptions',
        ),
        migrations.CreateModel(
            name='MedicalHistoryPrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('medical_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_app.medicalhistory')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_app.prescription')),
            ],
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='prescriptions',
            field=models.ManyToManyField(blank=True, through='hospital_app.MedicalHistoryPrescription', to='hospital_app.prescription'),
        ),
    ]
