# Generated by Django 5.1.3 on 2024-11-29 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0015_remove_medicalhistory_prescriptions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalhistory',
            name='is_dispatched',
            field=models.BooleanField(default=False),
        ),
    ]
