# Generated by Django 5.1.3 on 2024-11-29 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0016_medicalhistory_is_dispatched'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_days', models.PositiveIntegerField(default=0)),
                ('total_medicine_cost', models.PositiveIntegerField(default=0)),
                ('consultation_fee', models.PositiveIntegerField(default=200)),
                ('room_charge', models.PositiveIntegerField(default=0)),
                ('total_amount', models.PositiveIntegerField(default=0)),
                ('discharge_date', models.DateTimeField(auto_now_add=True)),
                ('bill_generated', models.BooleanField(default=False)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_app.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_app.doctor')),
                ('medical_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_app.medicalhistory')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_app.patient')),
                ('room_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital_app.roomtype')),
            ],
        ),
    ]
