# Generated by Django 5.1.3 on 2024-11-29 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0019_discharge_bill_payed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discharge',
            name='discharge_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
