# Generated by Django 5.1.3 on 2024-12-01 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0022_medicalhistory_is_inpatient'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='soft_deletion',
            field=models.BooleanField(default=False),
        ),
    ]
