# Generated by Django 5.1.3 on 2024-12-01 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0025_doctorreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorreview',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='hospital_app.patient'),
        ),
    ]
