# Generated by Django 5.1.3 on 2024-12-02 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0027_hospitalreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='discharge',
            name='insurance_applied',
            field=models.BooleanField(default=False),
        ),
    ]
